name: flutter_clean_arch_riverpod
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Widgets:
  cupertino_icons: ^1.0.8

  # State Management (Riverpod):
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  riverpod_generator: ^4.0.3

  # Network & API:
  dio: ^5.9.2

  # Data & Serialization:
  json_annotation: ^4.11.0
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0

  # Functional Programming:
  dartz: ^0.10.1

  # Localization (l10n):
  intl: ^0.20.2
  intl_utils: ^2.8.14
  flutter_localizations:
    sdk: flutter

  # Routing:
  auto_route: ^11.1.0
  auto_route_generator: ^10.4.0
  shared_preferences: ^2.5.5
  fl_chart: ^1.2.0
  mocktail: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.13.1
  json_serializable: ^6.13.0

flutter:
  generate: true
  uses-material-design: true
